import './global.css'

import { Providers } from './providers'

export const metadata = {
  title: 'Welcome to air',
  description: 'Generated by create-nx-workspace',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
